version = "v0.3"
modified = "2025-07-17T06:20:10.775562+00:00"

[a.a2]
description = "a.a2 credentials"
encrypted = "EAT3lpbVemlYRJQHCWWJNk7z0/W/7TvqSkGuKvQ="
salt = "f8gvr+VAcljwjopGsJDt2Q=="

[a.a11]
description = "a.a11 credentials"
encrypted = "DlerEY1WJ5jeNlxxYV0ofu4gI8Cb1LW+nnWY08w="
salt = "U/GE/NILXBs9PpuQSV5cvA=="

[b.a2]
description = "b.a2 credentials"
encrypted = "4J4c6AVZ/SLlLZB70G5v/0/a3LOjAahL/NvMov0="
salt = "UQEzm60DKL6ciqD41zh6OQ=="
