name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: vault
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: vault
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: vault
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: vault.exe
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - run: cargo build --release --target ${{ matrix.target }}
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.binary }}

  release:
    name: Create release and publish to npm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          path: binaries
      
      - name: Create archives
        run: |
          cd binaries
          tar czf vault-linux-x64.tar.gz -C x86_64-unknown-linux-gnu vault
          tar czf vault-macos-x64.tar.gz -C x86_64-apple-darwin vault
          tar czf vault-macos-arm64.tar.gz -C aarch64-apple-darwin vault
          zip vault-windows-x64.zip -j x86_64-pc-windows-msvc/vault.exe
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*.{tar.gz,zip}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Publish to npm
        run: |
          cd npm
          VERSION=${GITHUB_REF#refs/tags/v}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            npm version $VERSION --no-git-tag-version
          fi
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}